project_id = "lqrlvefeznfaauwgvubl"

[functions.perfectpay-webhook]
verify_jwt = false

[functions.meta-spend]
verify_jwt = false

[functions.meta-campaigns]
verify_jwt = false

[functions.run-reminders]
verify_jwt = false

[functions.google-auth-start]
verify_jwt = false

[functions.google-auth-callback]
verify_jwt = false

[functions.google-calendar-event]
verify_jwt = false
